# fly.toml app configuration file generated for qr-boxes on 2025-06-14T18:18:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qr-boxes'
primary_region = 'cdg'

[build]

[env]
PUBLIC_BACKEND_URL = 'https://qr-boxes-backend.fly.dev'

[http_service]
internal_port = 4321
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
